# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.grantrutherford.com
title: Grant Rutherford
email: grantrutherford@gmail.com
description: > # "Creative solutions for lifes problems and niggles"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/grantrutherford
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=142303076
